**Задание на повторение материала
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np

In [3]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a.reshape((2,6), order='C')

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape((2,6), order='F')

array([[12, 14, 16, 18, 20, 22],
       [13, 15, 17, 19, 21, 23]])

In [6]:
a.reshape((6,2), order='A')

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a.reshape((3,4), order='F')

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

In [8]:
a.reshape((4,3), order='F')

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
a.reshape((-1,2))
a.reshape((-1,3))
a.reshape((-1,4))
a.reshape((2,-1))
a.reshape((4,-1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

4Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
с точки зрения размерности numpy это двумерный массив

In [10]:
b = a.reshape((-1, 1))
a.shape

(12,)

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [11]:
r = np.random.normal(0, 1.0, (3, 4))
r

array([[ 0.83024147,  0.91455743, -0.18041124,  0.49013571],
       [-0.10109346,  0.98594406,  1.15587161, -0.11378632],
       [-1.77718407, -0.07936034, -0.32556304, -0.28822608]])

In [12]:
r.reshape((1, -1))

array([[ 0.83024147,  0.91455743, -0.18041124,  0.49013571, -0.10109346,
         0.98594406,  1.15587161, -0.11378632, -1.77718407, -0.07936034,
        -0.32556304, -0.28822608]])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [13]:
a = np.arange(20, 0, -2)
a.shape

(10,)

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [14]:
b = np.reshape(np.arange(20,0,-2), (1, -1))
b.shape

(1, 10)

a - 1D, b - 2D array

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [15]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.concatenate([a, b])
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [16]:
A = np.arange(12)
A = A.reshape((4, 3))
At = A.T
B = A @ At
print(np.linalg.det(B))
print(np.linalg.det(At @ A))

0.0
-1.0231815394945349e-11


Определитель матрицы B (4x4) равен 0 поэтому обратную матрицу не вычислить
Определитель матрицы At @ A (3x3) не равен 0 поэтому обратную матрицу можно вычислить

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [17]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [18]:
np.random.uniform(0, 16, 16)

array([ 5.9926419 , 15.2114289 , 11.71190307,  9.57853575,  2.49629825,
        2.49591233,  0.92933779, 13.85881833,  9.61784019, 11.32916124,
        0.32935191, 15.51855763, 13.31908225,  3.39742577,  2.90919948,
        2.93447216])